### ISSUE TITLE
Feature-request: NSCoding for Obj-c & Swift

### ISSUE THREAD

**Issue by skywinder** [Ahmed-Ali/JSONExport#11]
It would be nice to have ability to generate NSCoding protocol in methods also.

Awesome-awesome work! Thanks!

**Comment by Ahmed-Ali** [comment]
I thought about it and thought it might add some unwanted complixity for the generated files. However, I will try to give it a shot as soon as possible.

**Comment by skywinder** [comment]
@Ahmed-Ali Thanks! :+1: 
Probably it's better to implement it by checkbox below. (Then anybody will be able to disable unwanted code generation)

**Comment by Ahmed-Ali** [comment]
Yes that it is how I thought about it.

**Comment by roadst3r** [comment]
+1 yeah that would be awesome. Kinda miss it on the current release. Thanks!

**Comment by Ahmed-Ali** [comment]
I am still little bit busy, but I will go for it as soon as possible, I am also thinking about implementing NSCopying as well.
I will do my best to allocate some time for it next week.

**Comment by Ahmed-Ali** [comment]
Thanks for your valuable suggestions and requests.
Checkout the latest version.

**Comment by skywinder** [comment]
Thanks! :+1:
