### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by kevnm67** [Ahmed-Ali/JSONExport#124]
### Issue :construction:
- Checkbox text isn't visible when dark mode is enabled.

* Mac Mojave with dark mode enabled

## Current Behavior :mag:
- 'Constructor' and other checkbox text isn't visible.

### Steps to Reproduce
1. Run JsonExport using Mojave with dark mode enabled.

### Screen shots
<img width="1281" alt="screen_shot_2018-11-25_at_3_14_40_pm" src="https://user-images.githubusercontent.com/2734154/48984116-a9a22700-f0c5-11e8-8347-77a189b13b1d.png">

**Comment by PlutusCat** [comment]
You can edit this Main.storybiard
![image](https://user-images.githubusercontent.com/7953997/49054681-002b7480-f230-11e8-87d5-b357e5f68efd.png)
and recompile.
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/7953997/49054734-2cdf8c00-f230-11e8-9741-a557867f5a12.png">

**Comment by hzb** [comment]
@kevnm67 Hello, I have fixed this and submitted a PR to the developer, and you can use my version from https://github.com/hzb/JSONExport if you don't want to wait, or you can download the application from https://www.dropbox.com/s/20dm3241jdiwq7p/JSONExport.zip?dl=0, thank you.

**Comment by kevnm67** [comment]
@hzb I'll check it out.  Thanks!

**Comment by hzb** [comment]
@kevnm67 You are welcome. BTW if it works well, please close this issue, if not, please append the error, I will fix.

**Comment by kevnm67** [comment]
@hzb Will do.
