### ISSUE TITLE
Overriding specific property types

### ISSUE THREAD

**Issue by esbenvb** [Ahmed-Ali/JSONExport#13]
In our system we have a bunch of "type" fields which on the server and client are identified as ENUMs, but in between we use JSON and have to use strings for these fields.

Are you considering any support for overriding property types on specific classes, så the auto-generated code will have this ENUM for specific fields?

That would be nice - thanks!

**Comment by Ahmed-Ali** [comment]
I am not sure if I understand it correctly.
Can you post a json object with its expected/desired modal class to make it more clear what you are looking for?

**Comment by esbenvb** [comment]
transfer.json 

{  
   "recipientAccount":12321334,
   "senderAccount”:657432212,
   "amount":123.43,
   "recipientMessage":"hello world",
   "transferType":"BG"
}

in our case, transferType kan be the following values, among others:

BG, PG, KID, GIRO01, GIRO71 etc.

In our swift-based client and java-based server, we have an enumerator with the above values, and would like to map the transferType to this instead of handling the type as a string.

-- 
Esben von Buchwald
Sent with Airmail

On 10 Jun 2015 at 13:30:07, Ahmed Ali (notifications@github.com) wrote:

I am not sure if I understand it correctly.
Can you post a json object with its expected/desired modal class to make it more clear what you are looking for?

**Comment by Ahmed-Ali** [comment]
It is not possible for the application to guess that you want a type where the value is just string.
Of course it might be possible to add option so you can specify custom handling for specific, but this is very complex in implementation and usage.
