### ISSUE TITLE
Error: 'MyModel' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by skywinder** [Ahmed-Ali/JSONExport#20]
For Swift - Class

 'MyModel' cannot be constructed because it has no accessible initializers

all you have to do - is add `public` before init!

**Comment by Ahmed-Ali** [comment]
The default access level for classes is not public, so if you changed it to public, then yes you have to change the initializer access level as well.
But this is not an issue with JSONExport it self.

**Comment by skywinder** [comment]
agree  with you, thanks.
