### ISSUE TITLE
Xcode 7

### ISSUE THREAD

**Issue by marcelogfsouza** [Ahmed-Ali/JSONExport#23]
JSONExport is not being builded on Xcode 7 with the latest SDK version. It's ask to convert to Latest Swift Syntax, but doing this or not, it doesn't compile

![screen shot 2015-09-22 at 15 08 40](https://cloud.githubusercontent.com/assets/12305962/10028695/d9dacf70-613b-11e5-9319-83e7384a691d.png)

**Comment by Ahmed-Ali** [comment]
I will fix this as soon as possible, hopefully by next weekend maximum.

**Comment by Ahmed-Ali** [comment]
Fixed in the latest release 0.0.9
