### ISSUE TITLE
Swift - Mappable Issues

### ISSUE THREAD

**Issue by apocolipse** [Ahmed-Ali/JSONExport#24]
Firstly, with XCode 7 there have been updates to [ObjectMapper's](https://github.com/Hearst-DD/ObjectMapper) `Mappable` protocol, the init method is now generic and empty as follows:
```swift
required init?(_ map: Map){
}
```
This should go along with #23 

Additionally there's an issue with how classes are being created for `Mappable` types, here's some example generated code:
```swift
//
//  Response.swift
//  Model file Generated using JSONExport: https://github.com/Ahmed-Ali/JSONExport

import Foundation

class Response{

  var arbitraryCount : Int?
  var posts : [Post]?
  var meta : Meta?


  required init?(_ map: Map){

  }

  func mapping(map: Map)
  {
    arbitraryCount <- map["arbitrary_count"]
    if posts != nil{
      var dictionaryElements = [NSDictionary]()
      for postsElement in posts {
        dictionaryElements.append(postsElement.toDictionary())
      }
      dictionary["posts"] = dictionaryElements
    }
    if meta != nil{
      dictionary["meta"] = meta.toDictionary()
    }
    
  }

}
```

First and foremost is the lack of `: Mappable` after `Response`, it should look like
```swift
class Response: Mappable {
...
```

Secondly is the failure to simply map lists of mappable types.  I have a `Post` and `Meta` mappable type and the code generated is unnecessary and doesn't even look like it'll work...
It should look like:
```swift
...
  func mapping(map: Map)
  {
    arbitraryCount <- map["arbitrary_count"]
    posts          <- map["posts"]
    meta           <- map["meta"]
  }
...
```
(The `arbitraryCount` was just stuck into the JSON to illustrate that proper `Mappable` syntax does work for primitive types)

Still a very useful tool as its making it much easier to generate models for my complex types, I'm currently just manually fixing the above.

**Comment by Ahmed-Ali** [comment]
Hi @apocolipse,
Thanks for your support, currently I am busy with many other things, but I will apply this updates as soon as possible.
If you have some time and feel like you want to give it a try, please do and create a pull request.

Once more, thank you for your support.

**Comment by Ahmed-Ali** [comment]
Hi @apocolipse 
When you have the time, can you post a simple JSON object with the desired output so I can map it to the current state and update JSONExport accordingly.
Thanks
