### ISSUE TITLE
How to use JSONExport for array of array type of service?

### ISSUE THREAD

**Issue by sourabhsharmait** [Ahmed-Ali/JSONExport#27]
{"responseString":"Success","errorCode":1,"result":[[{"videoName":"Video Test","description":"Video Test","videoImage":"http:\/\/t1.gstatic.com\/images?q=tbn:ANd9GcQrRQrJ2OmPJNpwH6MU6pGSJGoYMVgOyozopoU3xgTtoUqxcbQM","categoryId":"1","categoryName":"TV Show","count":2},{"videoName":"video test 4","description":"Video Test","videoImage":"http:\/\/theonlinejournalist.com\/wp-content\/uploads\/2015\/05\/Priyanka-Chopra.jpg","categoryId":"1","categoryName":"TV Show","count":2}],[{"videoName":"Video Test 2","description":"Video Test","videoImage":"http:\/\/lifestylesz.com\/wp-content\/uploads\/2014\/02\/Priyanka-Chopra.jpg","categoryId":"2","categoryName":"Band","count":3},{"videoName":"video test 3","description":"Video Test","videoImage":"http:\/\/media.glamsham.com\/download\/wallpaper\/celebrities\/images\/p\/priyanka-chopra-wallpaper-114-12x9.jpg","categoryId":"2","categoryName":"Band","count":3},{"videoName":"video test 5","description":"Video Test","videoImage":"http:\/\/en.dailypakistan.com.pk\/wp-content\/uploads\/2015\/03\/priyanka-chopra-4225-1680x1050.jpg","categoryId":"2","categoryName":"Band","count":3}],[{"videoName":"Test 1","description":"","videoImage":"http:\/\/myapne.com\/news_images\/news_1443449687_7899e1717e0698d6e50364_1.jpg","categoryId":"3","categoryName":"Music","count":8},{"videoName":"Test 2","description":"","videoImage":"https:\/\/encrypted-tbn0.gstatic.com\/images?q=tbn:ANd9GcSIbOK6zbXK0PmxttPVVrh3hl6oYU9aQEXTPo32VRdn7Om3bir6","categoryId":"3","categoryName":"Music","count":8},{"videoName":"Test 3","description":"","videoImage":"http:\/\/1.bp.blogspot.com\/_uJ-SDPxtYh8\/TClt5l6f72I\/AAAAAAAAG0k\/OdQv75Hyjbw\/s1600\/SONAM+kapoor+(2).jpg","categoryId":"3","categoryName":"Music","count":8},{"videoName":"Test 4","description":"","videoImage":"https:\/\/encrypted-tbn2.gstatic.com\/images?q=tbn:ANd9GcRs7UQlBc3BEyQjBwvNgYzQI4ZCSmVgmqqdWQ5jbsJB-u2yek3E","categoryId":"3","categoryName":"Music","count":8},{"videoName":"Test 5","description":"","videoImage":"http:\/\/www.amicmaza.com\/wp-content\/uploads\/2012\/09\/Simple-beautiful-girl.jpg","categoryId":"3","categoryName":"Music","count":8},{"videoName":"Test 6","description":"","videoImage":"http:\/\/2.bp.blogspot.com\/-dKYXsPrDeU8\/T5ZD9NeNRfI\/AAAAAAAAB2Y\/P22RdR4-R48\/s1600\/pakistani+girls+photos+(645).jpg","categoryId":"3","categoryName":"Music","count":8},{"videoName":"Test 7","description":"","videoImage":"http:\/\/www.pkhykia.com\/wp-content\/uploads\/2014\/02\/Is-ko-kahte-ha-simple-girl.jpg","categoryId":"3","categoryName":"Music","count":8},{"videoName":"Test 9","description":"","videoImage":"http:\/\/1.bp.blogspot.com\/-NbmHZvpPG74\/TeDNcarKf5I\/AAAAAAAAC1c\/mRraMamUfNY\/s1600\/217554_103082809779610_100002336742079_28612_6306963_n.jpgg","categoryId":"3","categoryName":"Music","count":8}],[{"videoName":"Test 9","description":"Test","videoImage":"https:\/\/encrypted-tbn2.gstatic.com\/images?q=tbn:ANd9GcT8ozJlGP6EKgpM_lz7VUSow_gxx6XYr9fSnmIeHj2X9ekCFFgV","categoryId":"4","categoryName":"Dance","count":5},{"videoName":"Test 10","description":"Test3","videoImage":"http:\/\/pakifashion.com\/wp-content\/uploads\/2014\/11\/17736_452075081557853_83273622_n.jpg","categoryId":"4","categoryName":"Dance","count":5},{"videoName":"Test 11","description":"Test3","videoImage":"http:\/\/3.bp.blogspot.com\/-fx6BSTnEmnI\/VKpQFgmp48I\/AAAAAAAAU14\/sFI07qkFM8w\/s1600\/Bridal%2Bdress%2Bphoto%2B25.jpg","categoryId":"4","categoryName":"Dance","count":5},{"videoName":"Test 12","description":"Test3","videoImage":"http:\/\/2.bp.blogspot.com\/-TiaZfzO6ocM\/VIQB0422OwI\/AAAAAAAAUfs\/bCTd1WeuoXw\/s1600\/Bridal%2BMehndi%2Bdesign%2Bphoto%2B261.jpg","categoryId":"4","categoryName":"Dance","count":5},{"videoName":"Test 12","description":"Test3","videoImage":"http:\/\/www.shaadi-direct.com\/images\/members\/photos\/65339_7287483429.jpg","categoryId":"4","categoryName":"Dance","count":5}]]}

**Comment by Ahmed-Ali** [comment]
Actually this JSON object should export two classes instead of only the root class.
I will fix this issue as soon as possible.

**Comment by sourabhsharmait** [comment]
Hi Ahmed. I know that you are busy nowadays. But could you fix this issue asap?. Its a great tool made by you. Plz make it perfect. I want to contribute but i don't have much experience to fix this issue.

Thanks for great work.

**Comment by Ahmed-Ali** [comment]
Since nesting array of arrays of custom type is not something happens so often (at least in my experience), and it require lots of changes which I do not enough time for it at the moment; this will be put as a known limitation for the time being.
