### ISSUE TITLE
Something wrong, generate swift code

### ISSUE THREAD

**Issue by solszl** [Ahmed-Ali/JSONExport#33]
Hello 
I had just use your tool for autogenerating swift class by swiftyjson
but here some issues on it.
syntax warning or error
for example:
1:JSON.nullJSON is deprecated . new syntax is JSON.null
2:not import package, maybe it should be import package automatic,  import SwiftyJSON

some suggestions:
1: every file have a checkbox ,for merge into one file?

another one. use this tool generate struct swift file appear error yet
json content like this:
{  
"location": null  
}
then autogenerate file 
var location : AnyObject!
location = dictionary["location"] as? AnyObject
in new swift syntax it should be 
location = dictionary["location"] as AnyObjec! 
or define a optional variable  var location : AnyObject?

f.y.i

**Comment by Ahmed-Ali** [comment]
Will work on it as soon as possible
