### ISSUE TITLE
can swift variable whith default value?

### ISSUE THREAD

**Issue by huanghe810229530** [Ahmed-Ali/JSONExport#34]
class SwiftClass{

var address : Addres!
var isNonProfit : Bool!
var links : [Link]!
var name : String!
var page : Int!
var url : String!
}

because symbol "!" can take crash, so can above be this:
class SwiftClass{

var address : Addres?
var isNonProfit : Bool = false
var links : [Link] = []
var name : String = ""
var page : Int = 0
var url : String = ""
}
i want the blow variable effect, how can i get it?

**Comment by Ahmed-Ali** [comment]
Unfortunately, there is no plan for this at the moment. However, it should not be so hard to achieve.
