### ISSUE TITLE
In the App Store?

### ISSUE THREAD

**Issue by winkelsdorf** [Ahmed-Ali/JSONExport#37]
just fyi: https://itunes.apple.com/app/json-modeler/id991244863?mt=12

If it's not related to you: I hate it, when people just take OpenSource in order to make money..

👍 for JSONExport

**Comment by Ahmed-Ali** [comment]
I know about it a while ago... It is open source at the end, mostly, anyone can do whatever he wants.

**Comment by winkelsdorf** [comment]
Absolutely right, it's OpenSource under a relaxed license (looks like BSD 2-clause or MIT), so people are free to do whatever they want, but still I don't like that behavior. Removing the copyright is not ok.

Anyway, thank **you** for your work! It saved me a lot of time, by getting the Swift (Realm) classes directly out of existing JSON Data :)

**Comment by Ahmed-Ali** [comment]
Thank you @winkelsdorf !
Your contribution is always more than welcome!

**Comment by Ahmed-Ali** [comment]
Reported to Apple and it has been removed from the App Store :)

**Comment by winkelsdorf** [comment]
Glad to hear that 👍 :)
