### ISSUE TITLE
Implicitly Unwrapped Optionals.

### ISSUE THREAD

**Issue by mstfy** [Ahmed-Ali/JSONExport#40]
Very good work man. But there is one thing that bothers me. The tool generates implicitly unwrapped optionals for swift structs. I rather have my models nonoptional let. Is this configurable?

**Comment by Ahmed-Ali** [comment]
You will have to modify the language json file and replace the ? with ! to achieve this.
I wish this could have been the default, but since this is not common need, I don't think I will make it to be the default thing in JSON Export.
