### ISSUE TITLE
Mappable Not exporting to Swift 3 syntax

### ISSUE THREAD

**Issue by jejernig** [Ahmed-Ali/JSONExport#57]
When exporting Constructors and Utilities class is not conforming to the updated swift 3 NSCoding , Mappable protocols. Also decodeObjectForKey and encodeObject have been renamed to decodeObject(forKey:) / encodeObject(_:forKey:)

**Comment by Ahmed-Ali** [comment]
There is a PR for that which will be merged soon.

**Comment by Ahmed-Ali** [comment]
Check the latest version it has been updated to export object mapper for Swift 3.
Thanks for reporting it!
