### ISSUE TITLE
can't run project

### ISSUE THREAD

**Issue by JavenZ** [Ahmed-Ali/JSONExport#60]
network is bad，can't upload picture.

**Comment by Ahmed-Ali** [comment]
I can not help without any information on how to reproduce!

**Comment by JavenZ** [comment]
I'm sorry for reply late. When i open project, there a lot of error like this:
<img width="1132" alt="2016-10-08 10 53 29" src="https://cloud.githubusercontent.com/assets/17868438/19463672/9cc68012-9528-11e6-835b-90e6000c4e29.png">
I didn't modify anything……what happened？

macOS 10.12, xcode 7.2

**Comment by JavenZ** [comment]
![errorimage](https://cloud.githubusercontent.com/assets/17868438/19463840/ead12590-9529-11e6-8200-0c12d1a33e25.jpg)

**Comment by Ahmed-Ali** [comment]
The project requires Xcode 8 and Swift 3. Sorry forgot to update the README.MD for the latest version!
