### ISSUE TITLE
For dictionaries, getting wrong data types (Swift - structs)

### ISSUE THREAD

**Issue by 04it212** [Ahmed-Ali/JSONExport#62]
{
        "page_name": "Security Question validation",
        "page_flow": "forgot_password",
        "header": "Forgot your password?",
        "sub_header": "Just answer your security question",
        "fields": {
	        },
        "links": {
        },
        "buttons": {
        }
    }
<img width="1053" alt="screen shot 2016-10-26 at 3 34 01 pm" src="https://cloud.githubusercontent.com/assets/1214717/19742170/c1c0b062-9b91-11e6-8448-52bb8250ee2f.png">

**Comment by Ahmed-Ali** [comment]
The screenshot is for Java class.
Also I don't see what's wrong with the Button type?
Since it is object, it will translated into a class (or Struct in case of structs).

**Comment by 04it212** [comment]
I believe class should've been Field, Link and Button for three different maps according to JSON, instead constructed class created instance of only one class "Button"

**Comment by Ahmed-Ali** [comment]
JSONExport tries to avoid creating the same class with different name. For example if your JSON Object contains two fields like that
```JSON
{  
   "manager":{  
      "FirstName":"Manager's first name",
      "LastName":"Manager's last name"
   },
   "employee":{  
      "FirstName":"Employee's first name",
      "LastName":"Employee's last name"
   }
}```

JSONExport will treat them as an exact match and will pick the class name from the most recent match.

In your case all the three objects has the same exact fields (0 in your case), so JSONExport treats them as an exact type. Try to provide some fields of their possible data so JSONExport can better understand what they are.

**Comment by 04it212** [comment]
Ok. Thank you. Its really useful tool.
