### ISSUE TITLE
Problem with complex json

### ISSUE THREAD

**Issue by Navideck-fotis** [Ahmed-Ali/JSONExport#7]
I tried converting a relatively comlex json and it does not compile under xcode. It cannot find NSObject. After fixing this the are more errors with the initialisers.

This is the json I have trouble with:
{
  "standing": [
    {
      "sport_id": 2,
      "sport": "Basketball",
      "champ_id": 237,
      "champ": "NBA",
      "champ_full": "NBA",
      "period_id": 7317,
      "period": "2014-2015",
      "flag": "http://myurl.com/iphone/flags/nba_l.png",
      "standings": [
        {
          "definition": {
            "column_number": 11,
            "section_title": "NBA Ανατολή",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3267,
              "col_1": "1",
              "col_2": "Ατλάντα Χοκς",
              "col_3": "45",
              "col_4": "12",
              "col_5": "79%",
              "col_6": "0.0",
              "col_7": "26-4",
              "col_8": "19-8",
              "col_9": "6-4",
              "col_10": "W 2",
              "col_11": ""
            },
            {
              "team_id": 3261,
              "col_1": "2",
              "col_2": "Τορόντο Ράπτορς",
              "col_3": "37",
              "col_4": "20",
              "col_5": "65%",
              "col_6": "8",
              "col_7": "21-9",
              "col_8": "16-11",
              "col_9": "5-5",
              "col_10": "L 3",
              "col_11": ""
            },
            {
              "team_id": 3263,
              "col_1": "3",
              "col_2": "Κλίβελαντ Κάβαλίερς",
              "col_3": "37",
              "col_4": "22",
              "col_5": "63%",
              "col_6": "9",
              "col_7": "22-9",
              "col_8": "15-13",
              "col_9": "8-2",
              "col_10": "W 4",
              "col_11": ""
            },
            {
              "team_id": 3262,
              "col_1": "4",
              "col_2": "Σικάγο Μπουλς",
              "col_3": "36",
              "col_4": "22",
              "col_5": "62%",
              "col_6": "9.5",
              "col_7": "17-12",
              "col_8": "19-10",
              "col_9": "6-4",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3271,
              "col_1": "5",
              "col_2": "Ουάσινγκτον Γουίζαρντς",
              "col_3": "33",
              "col_4": "25",
              "col_5": "57%",
              "col_6": "12.5",
              "col_7": "20-10",
              "col_8": "13-15",
              "col_9": "2-8",
              "col_10": "L 5",
              "col_11": ""
            },
            {
              "team_id": 3266,
              "col_1": "6",
              "col_2": "Μιλγουόκι Μπακς",
              "col_3": "32",
              "col_4": "25",
              "col_5": "56%",
              "col_6": "13",
              "col_7": "17-11",
              "col_8": "15-14",
              "col_9": "6-4",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3269,
              "col_1": "7",
              "col_2": "Μαϊάμι Χιτ",
              "col_3": "25",
              "col_4": "31",
              "col_5": "45%",
              "col_6": "19.5",
              "col_7": "10-16",
              "col_8": "15-15",
              "col_9": "5-5",
              "col_10": "W 2",
              "col_11": ""
            },
            {
              "team_id": 3258,
              "col_1": "8",
              "col_2": "Μπρούκλιν Νετς",
              "col_3": "23",
              "col_4": "32",
              "col_5": "42%",
              "col_6": "21",
              "col_7": "10-15",
              "col_8": "13-17",
              "col_9": "5-5",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3268,
              "col_1": "9",
              "col_2": "Σαρλότ Χόρνετς",
              "col_3": "23",
              "col_4": "32",
              "col_5": "42%",
              "col_6": "21",
              "col_7": "13-16",
              "col_8": "10-16",
              "col_9": "4-6",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3264,
              "col_1": "10",
              "col_2": "Ντιτρόιτ Πίστονς",
              "col_3": "23",
              "col_4": "34",
              "col_5": "40%",
              "col_6": "22",
              "col_7": "12-19",
              "col_8": "11-15",
              "col_9": "6-4",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3265,
              "col_1": "11",
              "col_2": "Ιντιάνα Πέισερς",
              "col_3": "23",
              "col_4": "34",
              "col_5": "40%",
              "col_6": "22",
              "col_7": "12-14",
              "col_8": "11-20",
              "col_9": "7-3",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3257,
              "col_1": "12",
              "col_2": "Μπόστον Σέλτικς",
              "col_3": "22",
              "col_4": "33",
              "col_5": "40%",
              "col_6": "22",
              "col_7": "13-15",
              "col_8": "9-18",
              "col_9": "7-3",
              "col_10": "W 2",
              "col_11": ""
            },
            {
              "team_id": 3270,
              "col_1": "13",
              "col_2": "Ορλάντο Μάτζικ",
              "col_3": "19",
              "col_4": "40",
              "col_5": "32%",
              "col_6": "27",
              "col_7": "9-19",
              "col_8": "10-21",
              "col_9": "3-7",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3260,
              "col_1": "14",
              "col_2": "Φιλαδέλφεια 76ερς",
              "col_3": "12",
              "col_4": "45",
              "col_5": "21%",
              "col_6": "33",
              "col_7": "7-20",
              "col_8": "5-25",
              "col_9": "2-8",
              "col_10": "L 5",
              "col_11": ""
            },
            {
              "team_id": 3259,
              "col_1": "15",
              "col_2": "Νιου Γιορκ Νικς",
              "col_3": "10",
              "col_4": "46",
              "col_5": "18%",
              "col_6": "34.5",
              "col_7": "7-21",
              "col_8": "3-25",
              "col_9": "1-9",
              "col_10": "L 8",
              "col_11": ""
            }
          ],
          "legend": []
        },
        {
          "definition": {
            "column_number": 11,
            "section_title": "NBA Δύση",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3277,
              "col_1": "1",
              "col_2": "Γκ. Στ. Γουόριορς",
              "col_3": "44",
              "col_4": "11",
              "col_5": "80%",
              "col_6": "0.0",
              "col_7": "24-2",
              "col_8": "20-9",
              "col_9": "7-3",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3284,
              "col_1": "2",
              "col_2": "Μέμφις Γκρίζλις",
              "col_3": "41",
              "col_4": "15",
              "col_5": "73%",
              "col_6": "3.5",
              "col_7": "23-5",
              "col_8": "18-10",
              "col_9": "7-3",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3283,
              "col_1": "3",
              "col_2": "Χιούστον Ρόκετς",
              "col_3": "39",
              "col_4": "18",
              "col_5": "68%",
              "col_6": "6",
              "col_7": "21-8",
              "col_8": "18-10",
              "col_9": "6-4",
              "col_10": "W 3",
              "col_11": ""
            },
            {
              "team_id": 3274,
              "col_1": "4",
              "col_2": "Πόρτλαντ Τρέιλ Μπλέιζερς",
              "col_3": "37",
              "col_4": "19",
              "col_5": "66%",
              "col_6": "7.5",
              "col_7": "24-6",
              "col_8": "13-13",
              "col_9": "6-4",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3282,
              "col_1": "5",
              "col_2": "Ντάλας Μάβερικς",
              "col_3": "39",
              "col_4": "21",
              "col_5": "65%",
              "col_6": "7.5",
              "col_7": "20-9",
              "col_8": "19-12",
              "col_9": "5-5",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3278,
              "col_1": "6",
              "col_2": "Λ.A. Κλίπερς",
              "col_3": "37",
              "col_4": "21",
              "col_5": "64%",
              "col_6": "8.5",
              "col_7": "23-8",
              "col_8": "14-13",
              "col_9": "4-6",
              "col_10": "L 2",
              "col_11": ""
            },
            {
              "team_id": 3286,
              "col_1": "7",
              "col_2": "Σαν Αντόνιο Σπερς",
              "col_3": "34",
              "col_4": "23",
              "col_5": "60%",
              "col_6": "11",
              "col_7": "20-7",
              "col_8": "14-16",
              "col_9": "4-6",
              "col_10": "L 4",
              "col_11": ""
            },
            {
              "team_id": 4434,
              "col_1": "8",
              "col_2": "Οκλαχόμα Σίτι Θάντερ",
              "col_3": "32",
              "col_4": "26",
              "col_5": "55%",
              "col_6": "13.5",
              "col_7": "19-8",
              "col_8": "13-18",
              "col_9": "9-1",
              "col_10": "W 7",
              "col_11": ""
            },
            {
              "team_id": 3285,
              "col_1": "9",
              "col_2": "Νιού Ορλίνς Πέλικανς",
              "col_3": "30",
              "col_4": "27",
              "col_5": "53%",
              "col_6": "15",
              "col_7": "19-10",
              "col_8": "11-17",
              "col_9": "5-5",
              "col_10": "W 3",
              "col_11": ""
            },
            {
              "team_id": 3280,
              "col_1": "10",
              "col_2": "Φοίνιξ Σανς",
              "col_3": "31",
              "col_4": "28",
              "col_5": "53%",
              "col_6": "15",
              "col_7": "17-12",
              "col_8": "14-16",
              "col_9": "2-8",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3276,
              "col_1": "11",
              "col_2": "Γιούτα Τζαζ",
              "col_3": "21",
              "col_4": "35",
              "col_5": "38%",
              "col_6": "23.5",
              "col_7": "12-16",
              "col_8": "9-19",
              "col_9": "5-5",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3281,
              "col_1": "12",
              "col_2": "Σακραμέντο Κινγκς",
              "col_3": "20",
              "col_4": "35",
              "col_5": "36%",
              "col_6": "24",
              "col_7": "13-17",
              "col_8": "7-18",
              "col_9": "4-6",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3272,
              "col_1": "13",
              "col_2": "Ντένβερ Νάγκετς",
              "col_3": "20",
              "col_4": "37",
              "col_5": "35%",
              "col_6": "25",
              "col_7": "12-16",
              "col_8": "8-21",
              "col_9": "1-9",
              "col_10": "L 4",
              "col_11": ""
            },
            {
              "team_id": 3279,
              "col_1": "14",
              "col_2": "Λ.A. Λέικερς",
              "col_3": "15",
              "col_4": "41",
              "col_5": "27%",
              "col_6": "29.5",
              "col_7": "8-19",
              "col_8": "7-22",
              "col_9": "3-7",
              "col_10": "W 2",
              "col_11": ""
            },
            {
              "team_id": 3273,
              "col_1": "15",
              "col_2": "Μινεσότα Τίμπεργουλβς",
              "col_3": "13",
              "col_4": "43",
              "col_5": "23%",
              "col_6": "31.5",
              "col_7": "8-21",
              "col_8": "5-22",
              "col_9": "5-5",
              "col_10": "W 1",
              "col_11": ""
            }
          ],
          "legend": []
        },
        {
          "definition": {
            "column_number": 11,
            "section_title": "ΝΒΑ Ατλάντικ",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3261,
              "col_1": "1",
              "col_2": "Τορόντο Ράπτορς",
              "col_3": "37",
              "col_4": "20",
              "col_5": "65%",
              "col_6": "0.0",
              "col_7": "21-9",
              "col_8": "16-11",
              "col_9": "5-5",
              "col_10": "L 3",
              "col_11": ""
            },
            {
              "team_id": 3258,
              "col_1": "2",
              "col_2": "Μπρούκλιν Νετς",
              "col_3": "23",
              "col_4": "32",
              "col_5": "42%",
              "col_6": "13",
              "col_7": "10-15",
              "col_8": "13-17",
              "col_9": "5-5",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3257,
              "col_1": "3",
              "col_2": "Μπόστον Σέλτικς",
              "col_3": "22",
              "col_4": "33",
              "col_5": "40%",
              "col_6": "14",
              "col_7": "13-15",
              "col_8": "9-18",
              "col_9": "7-3",
              "col_10": "W 2",
              "col_11": ""
            },
            {
              "team_id": 3260,
              "col_1": "4",
              "col_2": "Φιλαδέλφεια 76ερς",
              "col_3": "12",
              "col_4": "45",
              "col_5": "21%",
              "col_6": "25",
              "col_7": "7-20",
              "col_8": "5-25",
              "col_9": "2-8",
              "col_10": "L 5",
              "col_11": ""
            },
            {
              "team_id": 3259,
              "col_1": "5",
              "col_2": "Νιου Γιορκ Νικς",
              "col_3": "10",
              "col_4": "46",
              "col_5": "18%",
              "col_6": "26.5",
              "col_7": "7-21",
              "col_8": "3-25",
              "col_9": "1-9",
              "col_10": "L 8",
              "col_11": ""
            }
          ],
          "legend": []
        },
        {
          "definition": {
            "column_number": 11,
            "section_title": "NBA Σεντραλ",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3263,
              "col_1": "1",
              "col_2": "Κλίβελαντ Κάβαλίερς",
              "col_3": "37",
              "col_4": "22",
              "col_5": "63%",
              "col_6": "0.0",
              "col_7": "22-9",
              "col_8": "15-13",
              "col_9": "8-2",
              "col_10": "W 4",
              "col_11": ""
            },
            {
              "team_id": 3262,
              "col_1": "2",
              "col_2": "Σικάγο Μπουλς",
              "col_3": "36",
              "col_4": "22",
              "col_5": "62%",
              "col_6": "0.5",
              "col_7": "17-12",
              "col_8": "19-10",
              "col_9": "6-4",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3266,
              "col_1": "3",
              "col_2": "Μιλγουόκι Μπακς",
              "col_3": "32",
              "col_4": "25",
              "col_5": "56%",
              "col_6": "4",
              "col_7": "17-11",
              "col_8": "15-14",
              "col_9": "6-4",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3264,
              "col_1": "4",
              "col_2": "Ντιτρόιτ Πίστονς",
              "col_3": "23",
              "col_4": "34",
              "col_5": "40%",
              "col_6": "13",
              "col_7": "12-19",
              "col_8": "11-15",
              "col_9": "6-4",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3265,
              "col_1": "5",
              "col_2": "Ιντιάνα Πέισερς",
              "col_3": "23",
              "col_4": "34",
              "col_5": "40%",
              "col_6": "13",
              "col_7": "12-14",
              "col_8": "11-20",
              "col_9": "7-3",
              "col_10": "L 1",
              "col_11": ""
            }
          ],
          "legend": []
        },
        {
          "definition": {
            "column_number": 11,
            "section_title": "NBA Σάουθιστ",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3267,
              "col_1": "1",
              "col_2": "Ατλάντα Χοκς",
              "col_3": "45",
              "col_4": "12",
              "col_5": "79%",
              "col_6": "0.0",
              "col_7": "26-4",
              "col_8": "19-8",
              "col_9": "6-4",
              "col_10": "W 2",
              "col_11": ""
            },
            {
              "team_id": 3271,
              "col_1": "2",
              "col_2": "Ουάσινγκτον Γουίζαρντς",
              "col_3": "33",
              "col_4": "25",
              "col_5": "57%",
              "col_6": "12.5",
              "col_7": "20-10",
              "col_8": "13-15",
              "col_9": "2-8",
              "col_10": "L 5",
              "col_11": ""
            },
            {
              "team_id": 3269,
              "col_1": "3",
              "col_2": "Μαϊάμι Χιτ",
              "col_3": "25",
              "col_4": "31",
              "col_5": "45%",
              "col_6": "19.5",
              "col_7": "10-16",
              "col_8": "15-15",
              "col_9": "5-5",
              "col_10": "W 2",
              "col_11": ""
            },
            {
              "team_id": 3268,
              "col_1": "4",
              "col_2": "Σαρλότ Χόρνετς",
              "col_3": "23",
              "col_4": "32",
              "col_5": "42%",
              "col_6": "21",
              "col_7": "13-16",
              "col_8": "10-16",
              "col_9": "4-6",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3270,
              "col_1": "5",
              "col_2": "Ορλάντο Μάτζικ",
              "col_3": "19",
              "col_4": "40",
              "col_5": "32%",
              "col_6": "27",
              "col_7": "9-19",
              "col_8": "10-21",
              "col_9": "3-7",
              "col_10": "L 1",
              "col_11": ""
            }
          ],
          "legend": []
        },
        {
          "definition": {
            "column_number": 11,
            "section_title": "NBA Νόρθγουεστ",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3274,
              "col_1": "1",
              "col_2": "Πόρτλαντ Τρέιλ Μπλέιζερς",
              "col_3": "37",
              "col_4": "19",
              "col_5": "66%",
              "col_6": "0.0",
              "col_7": "24-6",
              "col_8": "13-13",
              "col_9": "6-4",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 4434,
              "col_1": "2",
              "col_2": "Οκλαχόμα Σίτι Θάντερ",
              "col_3": "32",
              "col_4": "26",
              "col_5": "55%",
              "col_6": "6",
              "col_7": "19-8",
              "col_8": "13-18",
              "col_9": "9-1",
              "col_10": "W 7",
              "col_11": ""
            },
            {
              "team_id": 3276,
              "col_1": "3",
              "col_2": "Γιούτα Τζαζ",
              "col_3": "21",
              "col_4": "35",
              "col_5": "38%",
              "col_6": "16",
              "col_7": "12-16",
              "col_8": "9-19",
              "col_9": "5-5",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3272,
              "col_1": "4",
              "col_2": "Ντένβερ Νάγκετς",
              "col_3": "20",
              "col_4": "37",
              "col_5": "35%",
              "col_6": "17.5",
              "col_7": "12-16",
              "col_8": "8-21",
              "col_9": "1-9",
              "col_10": "L 4",
              "col_11": ""
            },
            {
              "team_id": 3273,
              "col_1": "5",
              "col_2": "Μινεσότα Τίμπεργουλβς",
              "col_3": "13",
              "col_4": "43",
              "col_5": "23%",
              "col_6": "24",
              "col_7": "8-21",
              "col_8": "5-22",
              "col_9": "5-5",
              "col_10": "W 1",
              "col_11": ""
            }
          ],
          "legend": []
        },
        {
          "definition": {
            "column_number": 11,
            "section_title": "NBA Πασίφικ",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3277,
              "col_1": "1",
              "col_2": "Γκ. Στ. Γουόριορς",
              "col_3": "44",
              "col_4": "11",
              "col_5": "80%",
              "col_6": "0.0",
              "col_7": "24-2",
              "col_8": "20-9",
              "col_9": "7-3",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3278,
              "col_1": "2",
              "col_2": "Λ.A. Κλίπερς",
              "col_3": "37",
              "col_4": "21",
              "col_5": "64%",
              "col_6": "8.5",
              "col_7": "23-8",
              "col_8": "14-13",
              "col_9": "4-6",
              "col_10": "L 2",
              "col_11": ""
            },
            {
              "team_id": 3280,
              "col_1": "3",
              "col_2": "Φοίνιξ Σανς",
              "col_3": "31",
              "col_4": "28",
              "col_5": "53%",
              "col_6": "15",
              "col_7": "17-12",
              "col_8": "14-16",
              "col_9": "2-8",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3281,
              "col_1": "4",
              "col_2": "Σακραμέντο Κινγκς",
              "col_3": "20",
              "col_4": "35",
              "col_5": "36%",
              "col_6": "24",
              "col_7": "13-17",
              "col_8": "7-18",
              "col_9": "4-6",
              "col_10": "W 1",
              "col_11": ""
            },
            {
              "team_id": 3279,
              "col_1": "5",
              "col_2": "Λ.A. Λέικερς",
              "col_3": "15",
              "col_4": "41",
              "col_5": "27%",
              "col_6": "29.5",
              "col_7": "8-19",
              "col_8": "7-22",
              "col_9": "3-7",
              "col_10": "W 2",
              "col_11": ""
            }
          ],
          "legend": []
        },
        {
          "definition": {
            "column_number": 11,
            "section_title": "NBA Σάουθγουεστ",
            "section_id": "standings"
          },
          "headers": [
            "",
            "Ομάδα",
            "Ν",
            "Η",
            "Ν%",
            "GB",
            "ΕΝ",
            "ΕΚ",
            "L10",
            "ST",
            ""
          ],
          "data": [
            {
              "team_id": 3284,
              "col_1": "1",
              "col_2": "Μέμφις Γκρίζλις",
              "col_3": "41",
              "col_4": "15",
              "col_5": "73%",
              "col_6": "0.0",
              "col_7": "23-5",
              "col_8": "18-10",
              "col_9": "7-3",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3283,
              "col_1": "2",
              "col_2": "Χιούστον Ρόκετς",
              "col_3": "39",
              "col_4": "18",
              "col_5": "68%",
              "col_6": "2.5",
              "col_7": "21-8",
              "col_8": "18-10",
              "col_9": "6-4",
              "col_10": "W 3",
              "col_11": ""
            },
            {
              "team_id": 3282,
              "col_1": "3",
              "col_2": "Ντάλας Μάβερικς",
              "col_3": "39",
              "col_4": "21",
              "col_5": "65%",
              "col_6": "4",
              "col_7": "20-9",
              "col_8": "19-12",
              "col_9": "5-5",
              "col_10": "L 1",
              "col_11": ""
            },
            {
              "team_id": 3286,
              "col_1": "4",
              "col_2": "Σαν Αντόνιο Σπερς",
              "col_3": "34",
              "col_4": "23",
              "col_5": "60%",
              "col_6": "7.5",
              "col_7": "20-7",
              "col_8": "14-16",
              "col_9": "4-6",
              "col_10": "L 4",
              "col_11": ""
            },
            {
              "team_id": 3285,
              "col_1": "5",
              "col_2": "Νιού Ορλίνς Πέλικανς",
              "col_3": "30",
              "col_4": "27",
              "col_5": "53%",
              "col_6": "11.5",
              "col_7": "19-10",
              "col_8": "11-17",
              "col_9": "5-5",
              "col_10": "W 3",
              "col_11": ""
            }
          ],
          "legend": []
        }
      ]
    }
  ]
}

**Comment by Ahmed-Ali** [comment]
I can see the cause of the issue. The JSON object you posted contains many empty values, which prevents JSONExport from being able to understand its type. Instead of just ignoring it silently, I decided to handle it as it were a custom object, which will cause errors and notify you where you need to fix it manually.

I will add this to the known issues.
