### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by Heisenbean** [Ahmed-Ali/JSONExport#77]
[`README`](https://github.com/Ahmed-Ali/JSONExport/blob/master/README.md) dosent write how to use it.
I was confused.

**Comment by wassimseif** [comment]
I wrote a blog post about it. Please check it out at [this link](https://blog.wassimseifeddine.com/2017/02/22/lets-talk-about-jsonexport/)
and share with me you feedback or if you need anymore help

**Comment by Heisenbean** [comment]
thanks very much
:)
