### ISSUE TITLE
Handle cases where Json contains "description" as key

### ISSUE THREAD

**Issue by Navideck-fotis** [Ahmed-Ali/JSONExport#8]
If a description exists as a key a special naming rule should be applied for this property because it conflicts with Objective-C's description property. You could prefix this property with the class name.

**Comment by Ahmed-Ali** [comment]
Sorry for my late replay.
Completely accepted suggestion and will work on it as soon as possible.

The special names I can think about right now are:
- description
- class
- id

Anything else?

**Comment by Ahmed-Ali** [comment]
You can checkout the develop branch, I have added a big list of reserved keywords for each language.
